%YAML:1.0

#--------------------------------------------------------------------------------------------
# System configuration file for 1 agent system
# Modified by Azmyin on 04_16_24
# Contains camera calibration parameters and file is Examples/Monocular directory for ease of use
#--------------------------------------------------------------------------------------------

# When the variables are commented, the system doesn't load a previous session or not store the current one

# If the LoadFile doesn't exist, the system give a message and create a new Atlas from scratch
#System.LoadAtlasFromFile: "Session_MH01_MH02_MH03_Mono"

# The store file is created from the current session, if a file with the same name exists it is deleted
#System.SaveAtlasToFile: "Session_MH01_MH02_MH03_Mono"

#--------------------------------------------------------------------------------------------
# Camera Parameters. Adjust them!
#--------------------------------------------------------------------------------------------
File.version: "1.0"

Camera.type: "PinHole"

# Camera calibration and distortion parameters (OpenCV)
Camera.fx: 262.04
Camera.fy: 262.04
Camera.cx: 322.68
Camera.cy: 180.18

# distortion parameters
Camera.k1: 0.0845
Camera.k2: -0.2303
Camera.p1: 0.0
Camera.p2: 0.0

# Camera resolution
Camera.width: 640
Camera.height: 480

# No idea where this is used
Camera.newWidth: 640
Camera.newHeight: 480

# Camera frames per second 
Camera.fps: 30

# Color order of the images (0: BGR, 1: RGB. It is ignored if images are grayscale)
Camera.RGB: 0

# Stereo baseline
Camera.bf: 38.72

# Depth map values are directly in 32-bit floating value
# TODO needs further investigation
DepthMapFactor: 1.0

# Close/Far threshold. Baseline times
ThDepth: 50.0

# Should be set for a stereo camera
# Close/Far threshold. Baseline times.
# Stereo.ThDepth: 40.0
# Stereo.b: 0.0745

#--------------------------------------------------------------------------------------------
# Parameters for the Python node
#--------------------------------------------------------------------------------------------

ORBSLAM3.sensorType: "MONOCULAR" # ORINIGIALLY STEREO


#--------------------------------------------------------------------------------------------
# ORB Parameters
#--------------------------------------------------------------------------------------------

# ORB Extractor: Number of features per image
#ORBextractor.nFeatures: 1250
ORBextractor.nFeatures: 750

# ORB Extractor: Scale factor between levels in the scale pyramid 	
ORBextractor.scaleFactor: 1.2

# ORB Extractor: Number of levels in the scale pyramid	
ORBextractor.nLevels: 8

# ORB Extractor: Fast threshold
# Image is divided in a grid. At each cell FAST are extracted imposing a minimum response.
# Firstly we impose iniThFAST. If no corners are detected we impose a lower value minThFAST
# You can lower these values if your images have low contrast			
ORBextractor.iniThFAST: 20
ORBextractor.minThFAST: 7

#--------------------------------------------------------------------------------------------
# Viewer Parameters
#---------------------------------------------------------------------------------------------
Viewer.KeyFrameSize: 0.05
Viewer.KeyFrameLineWidth: 1.0
Viewer.GraphLineWidth: 0.9
Viewer.PointSize: 2.0
Viewer.CameraSize: 0.08
Viewer.CameraLineWidth: 3.0
Viewer.ViewpointX: 0.0
Viewer.ViewpointY: -0.7
Viewer.ViewpointZ: -1.8
Viewer.ViewpointF: 500.0

